"""
Metadata Generator — 20 PM Apps
=================================
Just run it. No setup needed.
"""

import json
import os

METADATA = {
    "asana": {
        "name": "Asana",
        "category": "project_management",
        "subcategories": ["task_management", "workflow", "portfolio", "goals"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $11-$25 per user/mo",
        "primary_use_case": "Work management and project tracking for teams",
        "target_audience": ["mid_market", "enterprise", "marketing_teams", "product_teams"],
        "key_features": ["tasks", "timelines", "boards", "portfolios", "goals", "forms", "rules", "reporting"],
        "founded": 2008,
        "estimated_users": "20M+",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["monday", "clickup", "trello", "jira"],
    },
    "monday": {
        "name": "Monday.com",
        "category": "project_management",
        "subcategories": ["work_os", "crm", "dev", "marketing"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $9-$19 per seat/mo",
        "primary_use_case": "Work operating system with customizable workflows",
        "target_audience": ["mid_market", "enterprise", "cross_functional"],
        "key_features": ["boards", "dashboards", "automations", "integrations", "docs", "forms", "time_tracking"],
        "founded": 2012,
        "estimated_users": "225K+ orgs",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["asana", "clickup", "smartsheet"],
    },
    "clickup": {
        "name": "ClickUp",
        "category": "project_management",
        "subcategories": ["task_management", "docs", "whiteboards", "goals"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $7-$12 per user/mo",
        "primary_use_case": "All-in-one productivity platform replacing multiple tools",
        "target_audience": ["startups", "small_teams", "agencies", "developers"],
        "key_features": ["tasks", "docs", "whiteboards", "dashboards", "goals", "AI", "time_tracking", "sprints"],
        "founded": 2017,
        "estimated_users": "10M+",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["asana", "monday", "notion"],
    },
    "trello": {
        "name": "Trello",
        "category": "kanban",
        "subcategories": ["project_management", "task_management", "visual"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $5-$18 per user/mo",
        "primary_use_case": "Visual kanban-style project management",
        "target_audience": ["small_teams", "individuals", "non_technical"],
        "key_features": ["boards", "cards", "lists", "power_ups", "automation", "templates", "views"],
        "founded": 2011,
        "estimated_users": "50M+",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["asana", "monday", "notion"],
    },
    "jira": {
        "name": "Jira",
        "category": "issue_tracking",
        "subcategories": ["agile", "scrum", "kanban", "bug_tracking", "devops"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $8-$16 per user/mo",
        "primary_use_case": "Agile project management and issue tracking for software teams",
        "target_audience": ["enterprise", "developers", "engineering_teams"],
        "key_features": ["issues", "sprints", "boards", "roadmaps", "backlogs", "JQL", "workflows", "automation"],
        "founded": 2002,
        "estimated_users": "10M+",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["linear", "shortcut", "azure_devops"],
    },
    "notion": {
        "name": "Notion",
        "category": "all_in_one_workspace",
        "subcategories": ["docs", "wiki", "project_management", "database", "notes"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $10-$15 per user/mo",
        "primary_use_case": "All-in-one workspace for notes, docs, wikis, and project tracking",
        "target_audience": ["startups", "small_teams", "individuals", "product_teams"],
        "key_features": ["blocks", "databases", "templates", "wiki", "AI", "integrations", "projects"],
        "founded": 2016,
        "estimated_users": "30M+",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["coda", "airtable", "clickup"],
    },
    "todoist": {
        "name": "Todoist",
        "category": "task_management",
        "subcategories": ["personal_productivity", "to_do_lists", "habits"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $4-$6 per user/mo",
        "primary_use_case": "Personal and team task management with natural language input",
        "target_audience": ["individuals", "freelancers", "small_teams"],
        "key_features": ["tasks", "projects", "labels", "filters", "recurring_tasks", "natural_language", "karma"],
        "founded": 2007,
        "estimated_users": "40M+",
        "platforms": ["web", "desktop", "ios", "android", "browser_extension"],
        "competitors": ["ticktick", "microsoft_todo", "things3"],
    },
    "basecamp": {
        "name": "Basecamp",
        "category": "project_management",
        "subcategories": ["team_communication", "to_do_lists", "simple_pm"],
        "pricing_model": "flat_rate",
        "pricing_range": "$15/user/mo or $349/mo flat",
        "primary_use_case": "Simple project management and team communication",
        "target_audience": ["small_business", "agencies", "remote_teams"],
        "key_features": ["message_boards", "to_dos", "schedules", "docs", "campfire_chat", "hill_charts", "card_table"],
        "founded": 2004,
        "estimated_users": "3M+",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["asana", "monday", "teamwork"],
    },
    "linear": {
        "name": "Linear",
        "category": "issue_tracking",
        "subcategories": ["project_management", "bug_tracking", "sprint_planning", "developer_tools"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $8 per user/mo",
        "primary_use_case": "Streamlined issue tracking for software teams",
        "target_audience": ["developers", "engineering_teams", "startups"],
        "key_features": ["issues", "cycles", "projects", "roadmaps", "triage", "git_integration", "keyboard_shortcuts"],
        "founded": 2019,
        "estimated_users": "10K+ teams",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["jira", "shortcut", "github_issues"],
    },
    "airtable": {
        "name": "Airtable",
        "category": "database_spreadsheet",
        "subcategories": ["project_management", "crm", "content_calendar", "no_code"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $20-$45 per seat/mo",
        "primary_use_case": "Flexible database-spreadsheet hybrid for organizing anything",
        "target_audience": ["operations", "marketing", "product_teams", "non_technical"],
        "key_features": ["bases", "views", "automations", "interfaces", "extensions", "sync", "forms"],
        "founded": 2012,
        "estimated_users": "500K+ teams",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["notion", "smartsheet", "coda"],
    },
    "wrike": {
        "name": "Wrike",
        "category": "project_management",
        "subcategories": ["enterprise_pm", "resource_management", "proofing"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $10-$25 per user/mo",
        "primary_use_case": "Enterprise work management with advanced resource planning",
        "target_audience": ["enterprise", "professional_services", "marketing_teams"],
        "key_features": ["tasks", "gantt", "dashboards", "proofing", "resource_management", "time_tracking", "automation"],
        "founded": 2006,
        "estimated_users": "20K+ orgs",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["asana", "monday", "smartsheet"],
    },
    "smartsheet": {
        "name": "Smartsheet",
        "category": "project_management",
        "subcategories": ["enterprise_pm", "spreadsheet", "resource_management"],
        "pricing_model": "subscription",
        "pricing_range": "$9-$32 per user/mo",
        "primary_use_case": "Enterprise work execution platform with spreadsheet-like interface",
        "target_audience": ["enterprise", "IT", "operations", "PMO"],
        "key_features": ["sheets", "dashboards", "reports", "automation", "resource_management", "governance", "proofing"],
        "founded": 2005,
        "estimated_users": "10M+",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["wrike", "airtable", "monday"],
    },
    "teamwork": {
        "name": "Teamwork",
        "category": "project_management",
        "subcategories": ["client_work", "agencies", "time_tracking"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $6-$18 per user/mo",
        "primary_use_case": "Project management built for client work and agencies",
        "target_audience": ["agencies", "professional_services", "consultants"],
        "key_features": ["tasks", "milestones", "time_tracking", "budgets", "portfolios", "resource_scheduling", "invoicing"],
        "founded": 2007,
        "estimated_users": "45K+ teams",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["basecamp", "asana", "wrike"],
    },
    "hive": {
        "name": "Hive",
        "category": "project_management",
        "subcategories": ["task_management", "collaboration", "ai"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $5-$12 per user/mo",
        "primary_use_case": "AI-powered project management with flexible views",
        "target_audience": ["mid_market", "marketing_teams", "cross_functional"],
        "key_features": ["tasks", "gantt", "kanban", "calendar", "email_integration", "AI", "time_tracking", "forms"],
        "founded": 2015,
        "estimated_users": "Unknown",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["asana", "monday", "clickup"],
    },
    "height": {
        "name": "Height",
        "category": "project_management",
        "subcategories": ["task_management", "ai_native", "developer_tools"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $8.50 per user/mo",
        "primary_use_case": "AI-native project management that automates routine work",
        "target_audience": ["startups", "developers", "product_teams"],
        "key_features": ["tasks", "AI", "smart_lists", "chat", "sprints", "roadmaps", "cross_team_views"],
        "founded": 2020,
        "estimated_users": "Unknown",
        "platforms": ["web", "desktop"],
        "competitors": ["linear", "asana", "clickup"],
    },
    "shortcut": {
        "name": "Shortcut",
        "category": "issue_tracking",
        "subcategories": ["project_management", "developer_tools", "sprint_planning"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $8.50-$12 per user/mo",
        "primary_use_case": "Project management for software teams (formerly Clubhouse)",
        "target_audience": ["developers", "engineering_teams", "startups"],
        "key_features": ["stories", "epics", "iterations", "milestones", "roadmap", "git_integration", "docs"],
        "founded": 2016,
        "estimated_users": "Unknown",
        "platforms": ["web"],
        "competitors": ["linear", "jira", "github_issues"],
    },
    "plane": {
        "name": "Plane",
        "category": "issue_tracking",
        "subcategories": ["project_management", "open_source", "developer_tools"],
        "pricing_model": "freemium",
        "pricing_range": "Free (open source) / $7 per user/mo cloud",
        "primary_use_case": "Open-source project tracking alternative to Jira",
        "target_audience": ["developers", "startups", "open_source_teams"],
        "key_features": ["issues", "cycles", "modules", "views", "pages", "analytics", "self_hosted"],
        "founded": 2022,
        "estimated_users": "Unknown",
        "platforms": ["web"],
        "competitors": ["linear", "jira", "shortcut"],
    },
    "taskade": {
        "name": "Taskade",
        "category": "project_management",
        "subcategories": ["ai_agents", "collaboration", "mind_maps"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $8-$16 per user/mo",
        "primary_use_case": "AI-powered workspace with agents, tasks, and mind maps",
        "target_audience": ["small_teams", "individuals", "remote_teams"],
        "key_features": ["tasks", "AI_agents", "mind_maps", "video_chat", "templates", "automation", "calendar"],
        "founded": 2017,
        "estimated_users": "Unknown",
        "platforms": ["web", "desktop", "ios", "android", "browser_extension"],
        "competitors": ["notion", "clickup", "todoist"],
    },
    "nifty": {
        "name": "Nifty",
        "category": "project_management",
        "subcategories": ["milestones", "collaboration", "docs"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $7-$16 per user/mo",
        "primary_use_case": "All-in-one project management with milestone-driven progress",
        "target_audience": ["agencies", "small_teams", "consultants"],
        "key_features": ["tasks", "milestones", "docs", "discussions", "time_tracking", "portfolios", "forms"],
        "founded": 2017,
        "estimated_users": "Unknown",
        "platforms": ["web", "desktop", "ios", "android"],
        "competitors": ["asana", "basecamp", "teamwork"],
    },
    "ticktick": {
        "name": "TickTick",
        "category": "task_management",
        "subcategories": ["personal_productivity", "habits", "pomodoro"],
        "pricing_model": "freemium",
        "pricing_range": "Free / $36/year premium",
        "primary_use_case": "Personal task manager with habit tracking and pomodoro timer",
        "target_audience": ["individuals", "students", "freelancers"],
        "key_features": ["tasks", "habits", "pomodoro", "calendar", "kanban", "eisenhower_matrix", "natural_language"],
        "founded": 2013,
        "estimated_users": "10M+",
        "platforms": ["web", "desktop", "ios", "android", "browser_extension", "smartwatch"],
        "competitors": ["todoist", "microsoft_todo", "things3"],
    },
}


if __name__ == "__main__":
    print("📋 Generating metadata for 20 PM apps...\n")
    for app_key, meta in METADATA.items():
        os.makedirs(f"data/{app_key}", exist_ok=True)
        with open(f"data/{app_key}/metadata.json", "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2, ensure_ascii=False)
        print(f"  ✅ {app_key}")
    print(f"\n🎉 DONE. {len(METADATA)} metadata files.")
